### ISSUE TITLE
Why is it possible to set self.encrypt_passwords as False?

### ISSUE THREAD

**Issue by idgserpro** [zopefoundation/AccessControl#7]
I would like to know the exact motivation, if possible, of the ability to set self.encrypt_passwords to False by inheritance. Isn't this a security problem?

I'm trying to see if it's related to [Double encryption in manage_setUserFolderProperties](https://mail.zope.org/pipermail/zope-collector-monitor/2002-December/001449.html) or more info from http://dev.zope.org/Wikis/DevSite/Proposals/EncryptedUserfolderPasswords but collector and Wiki are dead (see https://github.com/zopefoundation/Zope/issues/31).

**Comment by dataflake** [comment]
I believe your assertion is wrong. You cannot acquire that attribute because it has a default value set at class level. Acquisition comes into play if an attribute cannot be found on the instance (including the class).

Just to make sure I have added a test in 86cbe76544cf7111af5898876e0b542770445a20 that tries to acquire the ``encrypt_passwords`` flag:

https://github.com/zopefoundation/AccessControl/blob/86cbe76544cf7111af5898876e0b542770445a20/src/AccessControl/tests/test_userfolder.py#L180-L196

You're welcome to follow up on this issue if you have a test case that proves your assertion.
